### ISSUE TITLE
ERROR:  Windows-only package

### ISSUE THREAD

**Issue by lucas-jardim** [ethanplunkett/gridprocess#1]
Dear Ethan,

I want to explore this package to run Compton resistant-kernel, but I received the error "ERROR:  Windows-only package" while installing the package. I am using an Ubuntu 20.3, how could I handle that?

Att,

**Comment by ethanplunkett** [comment]
Sadly there's no easy way to handle it.  The C++ code was written by a developer using a windows tool chain and is compiled outside of the R package and thus the package depends on Windows, so that error message is correct and there for a reason. 

I don't do a lot with C++ these days but years ago I made a version that compiled with R's tool chain.  Compiler differences in particular optimization in R's tool chain caused it to be buggy.  If you or others have interest in helping resolve those issues I could try to resurrect that code in a new package, but I don't have time to resolve them myself right now.

**Comment by lucas-jardim** [comment]
Thank you Ethan!!!
